--
-- SQL dump automatically generated by "spatialite_gui" [GPLv3]
-- created on: 2020-08-07 00:01:04
--
-- DB-file origin: C:\Users\Utente\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HFF-master\resources\dbfiles\hff_survey.sqlite
-- Table origin: "shipwreck_view"
--
-- intended target is: PostgreSQL + PostGIS
--

CREATE TABLE "public"."shipwreck_view" (
);


BEGIN;
COMMIT;

--
-- end SQL dump
--
